# Notebook Instructions

1. All the <u>code and data files</u> used in this course are available in the downloadable unit of the <u>last section of this course</u>.
2. You can run the notebook document sequentially (one cell at a time) by pressing **shift + enter**. 
3. While a cell is running, a [*] is shown on the left. After the cell is run, the output will appear on the next line.

This course is based on specific versions of python packages. You can find the details of the packages in <a href='https://quantra.quantinsti.com/quantra-notebook' target="_blank" >this manual</a>.

We will continue from where we left in the previous notebook.

# Notebook Contents

##### <span style="color:green">1. Indexing</span>
##### <span style="color:green">2. Slicing</span>
#####  <span style="color:green">3. Arrays of 1s and 0s</span>
##### <span style="color:green">4. Identity function</span>

## Indexing

We can access the elements of an array using its **index**. Index gives the location of an element of an array. 

- The first index is '0'.
- The second index is '1' and so on.
- The second last index is '-2'.
- The last index is '-1'.

### Indexing in a one-dimensional array

A one-dimensional array is indexed just like a list.

In [1]:
import numpy as np

# One dimensional array
A = np.array([10, 21, 32, 43, 54, 65, 76, 87])

# Print the first element of A
print(A[0])

# Remember, in pyhton, counting starts from 0 and not from 1

10


In [2]:
# Print the last element of A
print(A[-1])

87


In [3]:
# Print the third element of A
print(A[2])

32


In [4]:
# Print the second last element
print(A[-2])

76


### Indexing in a two-dimensional array

A 2-Dimensional Array consists of rows and columns, so you need to specify both rows and columns, to locate an element. 

In [5]:
# Create a 2-Dimensional Array
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(A)

# The shape of the array is : 4 rows and 3 columns

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# Print the element of Row 1, column 1
print(A[0][0])

1


In [7]:
# Print the element of row 2, column 1
print(A[1][0])

4


In [8]:
# Print the element of row 4, column 3
print(A[3][2])

12


In [9]:
# Another way to print the element of row 3, column 2
print(A[2, 1])

8


### Try on your own

In [ ]:
# Can you guess what will be the output of these print statement?
print(A[4, 3])

## Slicing 

When you want to select a certain section of an array, then you slice it. It could be a bunch of elements in a one-dimensional array and/or entire rows and columns in a two-dimensional array. 

### Slicing a one-dimensional array

You can slice a one-dimensional array in various ways:
- Print first few elements
- Print last few elements
- Print middle elements
- Print elements after certain step. 

Syntax: 
####  array_name [start: stop: step]


In [10]:
# Consider a one-dimensional array A
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# By default, the step = 1

# To print the first 4 elements (i.e. indices 0, 1, 2, 3, those before index 4)
print(A[:4])

# To print the elements from the index = 6 till the end
print(A[6:])

# To print the elements starting from index=2 and it will stop BEFORE index=5

print(A[2:5])

# To print all the elements of the array
print(A[:])

[1 2 3 4]
[7 8]
[3 4 5]
[1 2 3 4 5 6 7 8]


In [11]:
# Introducing step = 2

# This will print alternate index elements of the entire array, starting from index = 0
print(A[::2])

[1 3 5 7]


### Try on your own

In [12]:
# Can you guess what will be the output of these print statement?
print(A[::3])

[1 4 7]


### Slicing a two-dimensional array

You can slice a two-dimensional array in various ways:
- Print a row or a column
- Print multiple rows or columns
- Print a section of table for given rows and columns
- Print first and/or last rows and/or columns.
- Print rows and columns after certain step. 

Syntax: 
####  array_name [row start: row stop: row step], [col start, col stop, col step]

In [13]:
# A two-dimensional Array
A = np.array([
    ["00", "01", "02", "03", "04"],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44]
])

print(A)

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']
 ['30' '31' '32' '33' '34']
 ['40' '41' '42' '43' '44']]


In [14]:
# Print a row or a column
print(A[1, ])  # Printing Row 2

['10' '11' '12' '13' '14']


In [15]:
print(A[:, 1])  # Column 2

['01' '11' '21' '31' '41']


In [16]:
# Print multiple rows or columns

print(A[:2, ])  # Rows 1 & 2

print(A[:, 1:3])  # Columns 2 & 3

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']]
[['01' '02']
 ['11' '12']
 ['21' '22']
 ['31' '32']
 ['41' '42']]


In [17]:
# Print first or last rows and columns

print(A[:3, ])  # Printing first three rows

print(A[:, 3:])  # Printing 4th column and onwards

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']]
[['03' '04']
 ['13' '14']
 ['23' '24']
 ['33' '34']
 ['43' '44']]


In [18]:
# Print selected rows and columns
print(A[:2, 2])  # Rows 1 & 2 for column3

['02' '12']


In [19]:
print(A[:3, 2:])  # 1st three rows for the last three columns

[['02' '03' '04']
 ['12' '13' '14']
 ['22' '23' '24']]


In [20]:
print(A[:, :-2])  # Array without last two columns

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']
 ['30' '31' '32']
 ['40' '41' '42']]


In [21]:
print(A[:-3, :])  # Array without last 3 rows

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']]


### Using step

In [22]:
# Let us create a new array using the arange method for this exercise

# Create an array with 5 rows, 10 columns that has values from 0 to 49.
A2 = np.arange(50).reshape(5, 10)

print(A2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [23]:
# Using step in slicing

print(A2[::2, ])  # Print rows 1, 3, and 5

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]]


In [24]:
print(A2[:, 1:5:2])  # Print columns 2 & 4

[[ 1  3]
 [11 13]
 [21 23]
 [31 33]
 [41 43]]


In [25]:
print(A2[:, 1:10:2])  # Print columns 2,4, 6, 8, 10

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [26]:
# This will print an intersection of elements of rows 0, 2, 4 and columns 0, 3, 9, 6

print(A2[::2, ::3])

[[ 0  3  6  9]
 [20 23 26 29]
 [40 43 46 49]]


In [27]:
# Let us print all the rows and columns

print(A2[::, ::])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


### Try on your own

In [28]:
# If the following line of code is self explanatory to you, then you have understood the entire concept of 2D slicing

print(A2[2:4:1, 2:7:4])

[[22 26]
 [32 36]]


In [29]:
# This should be self explanatory

A = np.arange(12)
B = A.reshape(3, 4)

A[0] = 42
print(B)

[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Array of ones and zeros

We will be initialising arrays which have all the elements either as zeros or one. Such arrays help us while performing arithmetic operations

In [30]:
O = np.ones((4,4))
print(O)

# This is default datatype 'float'

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
O = np.ones((4, 4), dtype=int)  # Changing data type to integer
print(O)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [32]:
Z = np.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
Z = np.zeros((3,3), dtype = int)
print(Z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Identity function

An identity array has equal number of rows and columns. It is a square array so that the diagonal elements are all 'ones'. 

In [34]:
I = np.identity(4)

print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
I = np.identity(3, dtype=int)

print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In the upcoming Jupyter notebook, we will continue understanding about arrays and learn about vectorization, arithmetic operation, broadcasting and array comparisons.<br><br>