# Notebook Instructions

1. All the <u>code and data files</u> used in this course are available in the downloadable unit of the <u>last section of this course</u>.
2. You can run the notebook document sequentially (one cell at a time) by pressing **shift + enter**. 
3. While a cell is running, a [*] is shown on the left. After the cell is run, the output will appear on the next line.

This course is based on specific versions of python packages. You can find the details of the packages in <a href='https://quantra.quantinsti.com/quantra-notebook' target="_blank" >this manual</a>.

## Vectorization

Vectorization of code helps us write complex codes in a compact way and execute them faster. 

It allows to **operate** or apply a function on a complex object, like an array, "at once" rather than iterating over the individual elements. NumPy supports vectorization in an efficient way.

# Notebook Contents

##### <span style="color:green">1) 1D or 2D Array operations with a scalar</span>
##### <span style="color:green">2) 2D Array operations with another 2D array</span>
##### <span style="color:green">3) 2D Array operations with a 1D array or vector</span>
#####  <span style="color:green">4) Other operators: Compare & Logical</span>
##### <span style="color:green">5) Just for fun</span>

### Array operations with a scalar

Every element of the array is added/multiplied/operated with the given scalar. We will discuss:
- Addition
- Subtraction
- Multiplication

In [1]:
import numpy as np  # Start the notebook with importing the package

my_list = [1, 2, 3, 4, 5.5, 6.6, 7.123, 8.456]

V = np.array(my_list)  # Creating a 1D array or vector

print(V)

[1.    2.    3.    4.    5.5   6.6   7.123 8.456]


#### Vectorization using scalars - addition

In [2]:
V_a = V + 2 # Every element is increased by 2.

print(V_a)

[ 3.     4.     5.     6.     7.5    8.6    9.123 10.456]


#### Vectorization using scalars - subtraction

In [3]:
V_s = V - 2.4  # Every element is reduced by 2.4.

print(V_s)

[-1.4   -0.4    0.6    1.6    3.1    4.2    4.723  6.056]


#### Vectorization using scalars - multiplication

In [4]:
V2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Array of shape 3,3

V_m = V2 * 10  # Every element is multiplied by 10.

print(V2)
print(V_m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


#### Try on your own

In [5]:
V_e = V2 ** 2  # See the output and suggest what this operation is?

print(V_e)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 2D Array operations with another 2D array

This is only possible when the shape of the two arrays is same. For example, a (2,2) array can be operated with another (2,2) array. 


In [6]:
A = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])  # Array of shape 3,3
B = np.ones((3, 3))  # Array of shape 3,3
C = np.ones((4, 4))  # Array of shape 4,4
print(A)
print(B)
print(C)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# Addition of 2 arrays of same dimensions (3, 3)

print("Adding the arrays is element wise: ")

print(A + B)

Adding the arrays is element wise: 
[[  2.   3.   4.]
 [ 12.  23.  34.]
 [112. 223. 334.]]


In [8]:
# Addition of 2 arrays of different shapes or dimensions is NOT allowed

print("Addition of 2 arrays of different shapes or dimensions will throw a ValueError.")

print(A + C)

Addition of 2 arrays of different shapes or dimensions will throw a ValueError.


ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

In [9]:
# Subtraction of 2 arrays

print("Subtracting array B from A is element wise: ")

print(A - B)

Subtracting array B from A is element wise: 
[[  0.   1.   2.]
 [ 10.  21.  32.]
 [110. 221. 332.]]


In [10]:
# Multiplication of 2 arrays

A1 = np.array([[1, 2, 3], [4, 5, 6]])  # Array of shape 2,3
A2 = np.array([[1, 0, -1], [0, 1, -1]])  # Array of shape 2,3

print("Array 1", A1)
print("Array 2", A2)
print("Multiplying two arrays: ", A1 * A2)
print("As you can see above, the multiplication happens element by element.")

Array 1 [[1 2 3]
 [4 5 6]]
Array 2 [[ 1  0 -1]
 [ 0  1 -1]]
Multiplying two arrays:  [[ 1  0 -3]
 [ 0  5 -6]]
As you can see above, the multiplication happens element by element.


You can further try out various combinations yourself, in combining scalars and arithmetic operations to get a hand on vectorization.

### Broadcasting allows 2D Array operations with a 1D array or vector

NumPy also supports broadcasting. Broadcasting allows us to combine objects of <b>different shapes</b> within a single operation.

But, do remember that to perform this operation one of the matrices needs to be a vector with its length equal to one of the dimensions of the other matrix.

#### Try changing the shape of B and observe the results

In [11]:
import numpy as np

A = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])
B = np.array([1, 2, 3])

print(A)
print(B)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[1 2 3]


In [12]:
print("Multiplication with broadcasting: ")

print(A * B)

Multiplication with broadcasting: 
[[  1   4   9]
 [ 11  44  99]
 [111 444 999]]


In [13]:
print("... and now addition with broadcasting: ")

print(A + B)

... and now addition with broadcasting: 
[[  2   4   6]
 [ 12  24  36]
 [112 224 336]]


In [14]:
# Try to understand the difference between the two 'B' arrays

B = np.array([[1, 2, 3] * 3])

print(B)

[[1 2 3 1 2 3 1 2 3]]


In [15]:
B = np.array([[1, 2, 3], ] * 3)

print(B)

# Hint: look at the brackets

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [16]:
# Another example type

B = np.array([1, 2, 3])
B[:, np.newaxis]

# We have changed a row vector into a column vector

array([[1],
       [2],
       [3]])

In [17]:
# Broadcasting in a different way (by changing the vector shape)

A * B[:, np.newaxis]

array([[  1,   2,   3],
       [ 22,  44,  66],
       [333, 666, 999]])

In [18]:
# This example should be self explanatory by now

A = np.array([10, 20, 30])
B = np.array([1, 2, 3])
A[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [19]:
A[:, np.newaxis] * B

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

### Other operations

- Comparison operators: Comparing arrays and the elements of two similar shaped arrays
- Logical operators: AND/OR operands

In [20]:
import numpy as np

A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
B = np.array([[11, 102, 13], [201, 22, 203], [31, 32, 303]])

print(A)
print(B)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 11 102  13]
 [201  22 203]
 [ 31  32 303]]


In [21]:
# It will compare all the elements of the array with each other

A == B

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

In [22]:
# Will return 'True' only if each and every element is same in both the arrays

print(np.array_equal(A, B))

print(np.array_equal(A, A))

False
True


### Logical operators

In [23]:
# This should be self explanatory by now

a = np.array([[True, True], [False, False]])
b = np.array([[True, False], [True, False]])

print(np.logical_or(a, b))

[[ True  True]
 [ True False]]


In [24]:
print(np.logical_and(a, b))

[[ True False]
 [False False]]


This is where we will end our notebooks on NumPy. <br><br>